<?php

namespace AppBundle\Repository;

use AppBundle\Entity\CourtFee;
use AppBundle\Entity\Office;
use Doctrine\ORM\EntityRepository;

/**
 * CourtFeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourtFeeRepository extends EntityRepository
{
    public function getCourtFee(Office $office, $type)
    {
        $output = array();

        if($office->getType() == 'UDC'){
            $parentOffice = $office->getParent();
        } else {
            $parentOffice = $this->_em->getRepository('AppBundle:Office')->findOneBy(array('type' => 'MINISTRY'));
        }

        // Court Fee From Parent Office
        $courtFees = $this->findBy(array('office' => $parentOffice, 'applicationType' => $type, 'active' => true));
        if ($courtFees) {
            /** @var CourtFee $courtFee */
            foreach ($courtFees as $courtFee) {
                $output[$courtFee->getSurvey()->getId()] = array(
                    'normalCourtFee' => $courtFee->getNormalCourtFee(),
                    'urgentCourtFee' => $courtFee->getEmergencyCourtFee(),
                );
            }
        }

        // Court Fee From Own Office
        $courtFees = $this->findBy(array('office' => $office, 'applicationType' => $type, 'active' => true));
        if ($courtFees) {
            /** @var CourtFee $courtFee */
            foreach ($courtFees as $courtFee) {
                $output[$courtFee->getSurvey()->getId()] = array(
                    'normalCourtFee' => $courtFee->getNormalCourtFee(),
                    'urgentCourtFee' => $courtFee->getEmergencyCourtFee(),
                );
            }
        }

        return $output;
    }

    public function getSingleCourtFee(Office $office, $type)
    {
        $output = array();

        if($office->getType() == 'UDC'){
            $parentOffice = $office->getParent();
        } else {
            $parentOffice = $this->_em->getRepository('AppBundle:Office')->findOneBy(array('type' => 'MINISTRY'));
        }

        // Court Fee From Parent Office
        $courtFee = $this->findOneBy(array('office' => $parentOffice, 'applicationType' => $type, 'active' => true));
        /** @var CourtFee $courtFee */
        if ($courtFee) {
            $output['normalCourtFee'] = $courtFee->getNormalCourtFee();
            $output['urgentCourtFee'] = $courtFee->getEmergencyCourtFee();
        }

        // Court Fee From Own Office
        $courtFee = $this->findOneBy(array('office' => $office, 'applicationType' => $type, 'active' => true));
        /** @var CourtFee $courtFee */
        if ($courtFee) {
            $output['normalCourtFee'] = $courtFee->getNormalCourtFee();
            $output['urgentCourtFee'] = $courtFee->getEmergencyCourtFee();
        }

        return $output;
    }
}
