<?php

namespace Emicro\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Emicro\CoreBundle\Model\UtilityNew;

/**
 * GroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupRepository extends EntityRepository
{

}
