<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OfficeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HolidayRepository extends EntityRepository
{
    public function getHolidayOwnOfficeExit($date, $office){

        $qb = $this->createQueryBuilder('h');
        $qb->where('h.office = :office');
        $qb->setParameter('office', $office);
        $qb->orWhere($qb->expr()->isNull('h.office'));
        $qb->andWhere('h.date= :date');
        $qb->setParameter('date',$date);

        return $qb->getQuery()->getResult();

    }

}
