<?php

namespace AppBundle\Repository;

use AppBundle\Entity\SmsSetting;
use AppBundle\Entity\Office;
use Doctrine\ORM\EntityRepository;

/**
 * SmsSettingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SmsSettingRepository extends EntityRepository
{

    public function getSmsMessages(Office $office, $type)
    {
        $output = array();
        $type = $type == 'PORCHA_REQUEST' ? 'PORCHA': $type;

        if ($office->getType() == 'UDC'){
            $office = $office->getParent();
        }

        $smsMessages = $this->findBy(array('office' => $office, 'applicationType' => $type, 'active' => true));
        if ($smsMessages) {
            /** @var SmsSetting $smsMessage */
            foreach ($smsMessages as $smsMessage) {
                $output['newApplication'] = $smsMessage->getNewApplicationMessage();
                $output['changeDeliveryDate'] = $smsMessage->getDeliveryChangeMessage();
            }
        }

        return $output;
    }
}
