# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:

    sms.transporter:
        class: AppBundle\Service\SMSTransporter
        arguments: [%sms_api_endpoint%, %sms_api_username%, %sms_api_password%]

    ness.user_provider:
        class: UserBundle\Security\NessUserProvider
        arguments: [@service_container]

    ness.api_manager:
        class: UserBundle\Service\NessApiManager
        arguments: [%ness_api_endpoint%, %ness_api_username%, %ness_api_password%]

    app_authenticator:
        class:     UserBundle\Security\NessUserAuthenticator
        arguments: [@ness.api_manager, @doctrine.orm.default_entity_manager, @security.encoder_factory]

    app.twig_extension:
        class: LeaseBundle\Twig\CustomTwigExtensionForLease
        public: false
        tags:
            - { name: twig.extension }