<?php

namespace LeaseBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CitizenProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CitizenProfileRepository extends EntityRepository
{
}
