<?php

namespace LeaseBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    public function create($data) {

        $this->_em->persist($data);
        $this->_em->flush();
    }
}
