<?php

namespace LeaseBundle\Repository;

use Doctrine\ORM\EntityRepository;
use LeaseBundle\Entity\Market;

/**
 * marketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarketRepository extends EntityRepository
{
    public function create(Market $data)
    {
        $this->_em->persist($data);
        $this->_em->flush();
    }

    public function getAllMarketQueryBuilder()
    {
        return $this->createQueryBuilder('m');
    }
}
