<?php

namespace LeaseBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * WaterBodyDetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WaterBodyDetailsRepository extends EntityRepository
{
    public function delete($data)
    {
        $this->_em->remove($data);
        $this->_em->flush();
    }
}
