<?php

namespace PorchaProcessingBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ThanaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThanaRepository extends EntityRepository
{
}
