<?php

namespace PorchaProcessingBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UpozilaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UpozilaRepository extends EntityRepository
{
    public function getTotalMouzaForUpozila($upozila){
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('count(mouza.id)');
        $qb->where('mouza.upozila = :upozila');
        $qb->andWhere('mouza.approved = 1');
        $qb->setParameter('upozila', $upozila);

        $qb->from('PorchaProcessingBundle:Mouza','mouza');

        $count = $qb->getQuery()->getSingleScalarResult();
        return $count;

    }
    public function getTotalKhatianForUpozila($upozila,$surveyType){

        $qb = $this->getEntityManager()->getRepository('PorchaProcessingBundle:Khatian')->createQueryBuilder('k');
        $qb->join('k.mouza', 'm');
        $qb->join('k.volume', 'v');
        $qb->join('v.survey', 's');

        $qb->select('count(k.id)');
        $qb->where('v.upozila = :upozila');
        $qb->andWhere('s.type = :type');
        $qb->andWhere('k.archived = 1');
        $qb->setParameter('type', $surveyType);
        $qb->setParameter('upozila', $upozila);
        $count = $qb->getQuery()->getSingleScalarResult();
        return $count;
    }
}
