<?php

namespace PorchaProcessingBundle\Repository\ServiceRequest;

use Doctrine\ORM\EntityRepository;
use PorchaProcessingBundle\Entity\ServiceRequest;

/**
 * ServiceRequestAdditionalFeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdditionalFeeRepository extends EntityRepository
{

}
