<?php

namespace PorchaProcessingBundle\Repository\ServiceRequest;

use AppBundle\Service\OfficeManager;
use AppBundle\Traits\QueryAssistant;
use PorchaProcessingBundle\Entity\ServiceRequest;


/**
 * CorrectionRequestPorchaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CorrectionRequestPorchaRepository extends BaseRepository
{
    use QueryAssistant;

    /** @var OfficeManager */
    protected $officeManager;

    public function saveCorrectionRequest(ServiceRequest $serviceRequest, $serviceType)
    {
        $serviceType =  strtoupper($serviceType);
        $serviceRequest->setType($serviceType);
        $this->_em->persist($serviceRequest);
        $this->_em->flush();
    }

    /**
     * @param OfficeManager $officeManager
     * @return $this
     */
    public function setOfficeManager(OfficeManager $officeManager)
    {
        $this->officeManager = $officeManager;

        return $this;
    }
}
