workflow_team_list:
    path:     /team/list/{type}
    defaults:
        _controller: PorchaProcessingBundle:WorkflowTeam:teamList
        type: 'batch'
    methods: [GET]

workflow_team_new:
    path:     /team/new/{type}
    defaults:
        _controller: PorchaProcessingBundle:WorkflowTeam:new
        type: 'batch'
    methods: [GET]

workflow_team_edit:
    path:     /team/edit/{id}/{type}
    defaults:
        _controller: PorchaProcessingBundle:WorkflowTeam:editTeam
        type: 'batch'
    methods: [GET]

workflow_team_create:
    path:     /team/create/{type}
    defaults:
        _controller: PorchaProcessingBundle:WorkflowTeam:createTeam
        type: 'batch'
    methods: [POST]
    options:
        expose: true

workflow_team_update:
    path:     /team/update/{id}/{type}
    defaults:
        _controller: PorchaProcessingBundle:WorkflowTeam:updateTeam
        type: 'batch'
    methods: [POST]
    options:
        expose: true

workflow_team_delete:
    path:     /team/{id}/delete/{type}
    defaults:
        _controller: PorchaProcessingBundle:WorkflowTeam:deleteTeam
        type: 'batch'
    methods: [POST]
    options:
        expose: true

upozila_mouzas:
    path:     /team/{upozilas}/mouzas
    defaults: { _controller: PorchaProcessingBundle:MouzaOption:upozilaMouzas }
    options:
        expose: true